name: Issues-workflow
on: [push, issues, workflow_dispatch]
jobs:
  Display-Info: 
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo " ${{ toJson(github.event) }}"